

document.getElementById("boton").addEventListener('click', function() {
    document.getElementById("demo").innerHTML = "Soy casado y vivo con mi esposa y mi hija de 7 años de edad en la ciudad de Quequén. Somos una familia interesada en progresar y poder favorecer un futuro mejor para nuestra hija."
})


document.getElementById("Experiencia").addEventListener('click', function() {
        document.getElementById("expl").innerHTML = "En la Ferretería me desempeñaba como encargado de cajas y de atención al público. En la Policía Bonaerense llevo 9 años de labor, durante los cuales, me desempeñé como encargado de tercio y como oficial de Servicio (Es el que se encuentra a cargo del servicio, dispone las labores a realizarse, controla que se realice todo como se debe y el que debe escribir todo lo que suceda en el servicio). Durante estos años tuve muchos subordinados, como así también, distintos superiores. En todos los casos, siempre traté de que haya el mejor ambiente laborar y de realizar las labores asignadas por mis superiores"
})

document.getElementById("est").addEventListener('click', function() {
    document.getElementById("educ").innerHTML = "Luego de finalizar los cursos de programación y, que pueda obtener un trabajo que me permita cubrir una carrera universitaria, mi intención es seguir perfeccionándome e indagando en la rama de seguridad cibernética. Quisiera seguir estudiando, ya que, gusto de poder desenvolverme de manera correcta en todos los ámbitos en los que me toque desempeñar mi trabajo."
})